// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckPythonAvailable():Promise<boolean|string>;

export function FetchPorbsFromServer():Promise<Array<main.ProbJSON>|boolean>;

export function Greet(arg1:string):Promise<string>;

export function LoadUserData():Promise<main.UserData|boolean>;

export function RunPythonCode(arg1:string):Promise<string|boolean>;

export function SaveUserData(arg1:main.UserData):Promise<boolean>;
